# Generated by Django 5.0 on 2024-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='availabletime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availabletime',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
